pipeline {
    agent { label 'Jenkins-Agent' }

    tools {
        jdk "Java17"
        maven "Maven3"
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }
            
        stage('Checkout from SCM') {
            steps {
                // Get some code from a GitHub repository
                git branch: 'main', credentialsId: 'github', url: 'https://github.com/Hatsuhinode/DevOps-01.git'
            }
        }
            
        stage('Build Application') {
            steps {
                // Navigate to the application directory
                dir('Register-app/application') {
                    // Run Maven commands
                    sh 'mvn clean package'
                }
            }
        }
            
        stage('Test Application') {
            steps {
                // Navigate to the application directory
                dir('Register-app/application') {
                    // Run Maven commands
                    sh 'mvn test'
                }
            }
        }
    }
}
