---
- name: Install Docker on Ubuntu
  hosts: localhost
  become: yes

  tasks:
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - ca-certificates
        - curl
      become: yes

    - name: Create directory for apt keyrings
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      become: yes

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
      become: yes

    - name: Add Docker repository to Apt sources
      lineinfile:
        dest: /etc/apt/sources.list.d/docker.list
        line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        create: yes
      become: yes

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name: 
          - docker.io
        state: present
      become: yes

